### ISSUE TITLE
Will you be adding a script to pretrain LLAMA2?

### ISSUE THREAD

**Issue by erastogi** [epfLLM/Megatron-LLM#1]
I see that the script `finetune.py` could be used to pretrain LLAMA2. I am looking forward to do continued-pretraining of Llama2 and was wondering what is the best way to load the llam2 weights in the pretrain.py script so that the pretraining does not start from scratch

**Comment by martinjaggi** [comment]
yes you can use the [finetune.py](https://github.com/epfLLM/Megatron-LLM/blob/main/finetune.py) for continued pre-training of llama2. that's what we're using it for also

**Comment by brewswang** [comment]
Can you send me the complete parameters related to training llama2 using finetune. py?

**Comment by martinjaggi** [comment]
You find parameters in [finetune.sh#L67-L104](https://github.com/epfLLM/Megatron-LLM/blob/740ab3d9a57774601742fb93c0b74653cc20807e/examples/finetune.sh#L67-L104). I assume that's what you asked for?

**Comment by AleHD** [comment]
More information about how to finetune llama can be found in the [getting started guide](https://epfllm.github.io/Megatron-LLM/guide/getting_started.html), the parameters can be found as metioned in [finetune.sh#L67-L104](https://github.com/epfLLM/Megatron-LLM/blob/740ab3d9a57774601742fb93c0b74653cc20807e/examples/finetune.sh#L67-L104), but also are stated in [the FAQ](https://epfllm.github.io/Megatron-LLM/guide/faq.html#what-arguments-are-used-to-train-llama-2).
