### ISSUE TITLE
HF LLaMA -> megatron weight

### ISSUE THREAD

**Issue by dumpmemory** [epfLLM/Megatron-LLM#10]
Could you provide the script to convert hf llama or llama2 to megatron weight ? Thanks

**Comment by martinjaggi** [comment]
there is a folder named after it: 
https://github.com/epfLLM/Megatron-LLM/blob/main/weights2megatron/

**Comment by martinjaggi** [comment]
you're right. sorry we'll reopen the issue. BTW the megatron2HF converter (other direction) has just been improved and should work with no issue
