### ISSUE TITLE
Introduce Sailor Models

### ISSUE THREAD

**Issue by longxudou** [epfLLM/Megatron-LLM#105]
Hello! We have used Megatron-LLM in our Sailor project. 

It is a suite of Open Language Models tailored for South-East Asia (SEA), focusing on languages such as 🇮🇩Indonesian, 🇹🇭Thai, 🇻🇳Vietnamese, 🇲🇾Malay, and 🇱🇦Lao.

Please see [Sailor homepage](https://sailorllm.github.io/) for more details. 
We also reference Megatron-LLM in Section 5.1 of the [Sailor Report](https://arxiv.org/pdf/2404.03608).

Thanks for for building the excellent codebase and presenting the detailed document!

**Comment by martinjaggi** [comment]
many thank for letting us know. i added a link in our readme. 
keep us posted!
