### ISSUE TITLE
convert_llama2hf.py should be replaced with newer version

### ISSUE THREAD

**Issue by andreaskoepf** [epfLLM/Megatron-LLM#17]
The weights2megatron directory contains the script [convert_llama2hf.py](https://github.com/epfLLM/Megatron-LLM/blob/main/weights2megatron/convert_llama2hf.py) which looks very similar to (an old version of) [convert_llama_weights_to_hf.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py). The only difference seems to be a custom parameter for `max_shard_size` ... 

The current version of [convert_llama_weights_to_hf.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py) of HF transformers has support for Llama2, e.g. 70B variant and MQA (`n_kv_heads != n_heads`).

**Comment by martinjaggi** [comment]
fixed by https://github.com/epfLLM/Megatron-LLM/commit/3bc529c9652b25722b8084a32bce4ae548eac598 by @Olivia-fsm i guess?

**Comment by Olivia-fsm** [comment]
The issue has been solved. You can refer to `megatron2hf.sh` for the detailed instructions :)

**Comment by andreaskoepf** [comment]
This is about the conversion of llama weights and the existence of an outdated version of convert_llama2hf.py in this repository. This has not been addressed for solved yet.

**Comment by andreaskoepf** [comment]
I created a corresponding PR https://github.com/epfLLM/Megatron-LLM/pull/25 to fix this specific issues (llama2hf conversion script, not megatron2hf). Alternatively [convert_llama2hf.py](https://github.com/epfLLM/Megatron-LLM/blob/main/weights2megatron/convert_llama2hf.py) could be deleted from this repository if no longer required.
