### ISSUE TITLE
Falcon unusually high loss

### ISSUE THREAD

**Issue by andreaskoepf** [epfLLM/Megatron-LLM#2]
In [weights2megatron/README.md](https://github.com/epfLLM/Megatron-LLM/blob/main/weights2megatron/README.md) it says:

"We are experiencing unusually high loss in falcon even when loading from a validated checkpoint. We are working to fix this..."

Is this still an open issue?

**Comment by martinjaggi** [comment]
my impression was this is fixed already. @AleHD can confirm

**Comment by AleHD** [comment]
Yes, it was fixed. I'll update the README.md

**Comment by AleHD** [comment]
Information updated with [8f526a1](https://github.com/epfLLM/Megatron-LLM/commit/8f526a1258f058458248066dd5bb5e0d257bb786).
