### ISSUE TITLE
Add falcon support in megatron2hf.py

### ISSUE THREAD

**Issue by AleHD** [epfLLM/Megatron-LLM#28]

**Comment by andreaskoepf** [comment]
Is someone already working on this? Otherwise you could assign me please.

**Comment by AleHD** [comment]
Nobody is working on it at the moment, go for it

**Comment by malteos** [comment]
I implemented the basic megatron to HF convertion for falcon7b-like models. See https://gist.github.com/malteos/85fd117cb0ba4cd28882464026252ee9

The implementation is still pretty much WIP and requires manually downloading the RWModel + RWConfig files from HF hub.
