### ISSUE TITLE
How to convert Megatron -> Huggingface weights?

### ISSUE THREAD

**Issue by andreaskoepf** [epfLLM/Megatron-LLM#3]
Did you maybe also write the counterpart of [weights2megatron.py](https://github.com/epfLLM/Megatron-LLM/blob/main/weights2megatron/weights2megatron.py) to convert megatron checkpoints back to huggingface format? Or is there a standard tool for this process somewhere else available? Would it be useful to create such a script?

**Comment by martinjaggi** [comment]
we're working on adding this converter (as it's useful for eval), should be ready this week

**Comment by martinjaggi** [comment]
was resolved in [26e78ae](https://github.com/epfLLM/Megatron-LLM/commit/26e78ae53d8b87323678fc800ea26bbd05f09985)
