### ISSUE TITLE
convert huggingface model to megatron. "Only llama v2 available using huggingface"

### ISSUE THREAD

**Issue by uygnef** [epfLLM/Megatron-LLM#49]
Hi @AleHD 

When I run this script:

python weights2megatron/weights2megatron.py llama --size=7 

--out=/path/to/megatron/weights/ --cache-dir=/path/to/llama-7b/

It says:

assert version == 2, "Only llama v2 available using huggingface"
Does this script not support Llama v1?

**Comment by AleHD** [comment]
At the moment you need to specify the cache directory to the weights given officialy by meta. We are working on using [decapoda-research](https://huggingface.co/decapoda-research/llama-7b-hf) llama implementation to retrieve the weights automatically with huggingface.
