### ISSUE TITLE
finetune.py: error: unrecognized arguments: --use_multiquery_attn

### ISSUE THREAD

**Issue by andreaskoepf** [epfLLM/Megatron-LLM#5]
Calling `examples/finetune.sh falcon --size 7 --tp 1 --pp 2 --gpus 8 --global-batch 8` I get the error `finetune.py: error: unrecognized arguments: --use_multiquery_attn` (the argument is added in [finetune.sh#L65](https://github.com/epfLLM/Megatron-LLM/blob/8f526a1258f058458248066dd5bb5e0d257bb786/examples/finetune.sh#L65)). This argument seems not to be defined in [arguments.py](https://github.com/epfLLM/Megatron-LLM/blob/main/megatron/arguments.py). Is it save to simply leave it away?

**Comment by AleHD** [comment]
Fixed with [6aa2532](https://github.com/epfLLM/Megatron-LLM/commit/6aa25324abbc804a0292dce1bb106894289126ce).
