### ISSUE TITLE
dose 8 A100 80g enough to finetune 70b llama2  ?

### ISSUE THREAD

**Issue by james2v** [epfLLM/Megatron-LLM#52]

**Comment by panx27** [comment]
I think the minimum is 32 * A100 80GB
https://github.com/epfLLM/Megatron-LLM/blob/main/docs/guide/faq.md#what-are-the-basic-hardware-requirements

**Comment by james2v** [comment]
> I think the minimum is 32 * A100 80GB https://github.com/epfLLM/Megatron-LLM/blob/main/docs/guide/faq.md#what-are-the-basic-hardware-requirements

THANK YOU！ I might tune 70b llama2 with lora then.

**Comment by AleHD** [comment]
Correct, 32x 80GB is the minimum requirement we have been able to achieve

**Comment by JumpingRain** [comment]
> > I think the minimum is 32 * A100 80GB https://github.com/epfLLM/Megatron-LLM/blob/main/docs/guide/faq.md#what-are-the-basic-hardware-requirements
> 
> THANK YOU！ I might tune 70b llama2 with lora then.

can you run llama2 70b with lora.

**Comment by james2v** [comment]
> > > I think the minimum is 32 * A100 80GB https://github.com/epfLLM/Megatron-LLM/blob/main/docs/guide/faq.md#what-are-the-basic-hardware-requirements
> > 
> > 
> > THANK YOU！ I might tune 70b llama2 with lora then.
> 
> can you run llama2 70b with lora.

i load it  in 8 bit to train it. but i use other hud to run it
