### ISSUE TITLE
Minimum number of 80GB GPUs to train Falcon-40B or Llama2-70B?

### ISSUE THREAD

**Issue by andreaskoepf** [epfLLM/Megatron-LLM#6]
What is the minimum number of 80 GB GPUs required to train Falcon-40B or Llama2-70B and what are working/best TP/PP configurations?

So far it seems a single 8x A100 80 GB node is not enough even for Falcon-40B. I tried with TP 8, after model loading ~50 GB GPU memory are allocated, it goes OOM when processing the first batch.

**Comment by andreaskoepf** [comment]
For llama2 70B this has now been answered in the FAQ section of the documentation: [What are the basic hardware requirements?](https://epfllm.github.io/Megatron-LLM/guide/faq.html#what-are-the-basic-hardware-requirements)

**Comment by AleHD** [comment]
Just updated it to include Falcon 40B numbers too.
