### ISSUE TITLE
Feature Request: Can we directly use the huggingface dataset for training

### ISSUE THREAD

**Issue by dumpmemory** [epfLLM/Megatron-LLM#65]
Can we use huggingface dataset instead of megatron style for training.

**Comment by kylematoba** [comment]
hi, did you see this https://epfllm.github.io/Megatron-LLM/guide/weights_conversion.html?

**Comment by martinjaggi** [comment]
for the weights, conversion to and from HF is already well supported

for dataset loaders, we currently stick to the megatron-LM one and the pipeline also used by open assistant.

if people agree the other data loader would be beneficial and is proven to work well in the distributed setting, feel free to re-open and/or file a PR
