### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (29056x22016 and 11008x4096)

### ISSUE THREAD

**Issue by liuxm117** [epfLLM/Megatron-LLM#73]
![image](https://github.com/epfLLM/Megatron-LLM/assets/50068070/29d6e8fb-b155-47ec-a620-c905b14da5e6)
hi, can you help to see what could be the cause of this error？

**Comment by kylematoba** [comment]
We'll need more information about the model to be of any help. Please reopen with a MWE (preferable) or at least some details of what you're trying to do.

**Comment by liuxm117** [comment]
i use tp=1, pp=2 for llama2 7B finetune，
