### ISSUE TITLE
Correctness when enabling FlashAttention + Sequence Parallel at the same time?

### ISSUE THREAD

**Issue by xingyaoww** [epfLLM/Megatron-LLM#99]
It just occurred to me recently that the current implementation of FlashAttention does not account for the cases of sequence parallelism.

For example, [here](https://github.com/epfLLM/Megatron-LLM/blob/1b06b129fa463b7bfce88ef49e2082f8df00c7fa/megatron/model/transformer.py#L548-L552) the `self.core_attention_flash` is called (which is essentially `flash_attn.flash_attn_func`),  however, the `q, k, v` passed into flash attention are *not* all-gathered, which means we only calculate attention on a chunk of sentences (say total seq_len is `L`, parallelism being 4, we only calculate attention within `L/4` sequence) which will cause issues in the trained models (i.e., the trained model stop attending to previous content after `L/4` tokens).

Their original implementation of `ParallelAttention` does not have this issue since they perform all-gather in the forward pass and reduce-scatter in the backward pass; see [this issue](https://github.com/NVIDIA/Megatron-LM/issues/357) for details.

**Comment by martinjaggi** [comment]
we haven't modified this aspect compared to nvidia megatron. are you saying that in nvidia megatron this has been changed since we forked the repository (around april 2023)?

**Comment by xingyaoww** [comment]
Yes, this is the same implementation as Megatron-LM. Never mind, I just dig in deeper to do some interactive debugging and found out the `all-gather` operation happens implicitly in `self.query_key_value`, which is a `ColumnParallelLinear` that helps take care of the all-gather. The current implementation should be fine. :)
